# ~/.config/starship.toml

format = '$shell${custom.hostname_ssh_agent}${custom.hostname_no_ssh_agent}$directory$character'
add_newline = false


[shell]
disabled = false
format = "[$indicator]($style)"
style = "bold blue"
bash_indicator = "\\[bash\\]($style) "
# zsh_indicator = "\\[zsh\\]($style) "
zsh_indicator = ""
fish_indicator = "\\[fish\\]($style) "

[custom.hostname_ssh_agent]
command = "hostname -s"
format = "[\\($output\\)]($style) "
style = "bold bright-yellow"
when = 'test -n "$SSH_CONNECTION" && test -S "$SSH_AUTH_SOCK"'

[custom.hostname_no_ssh_agent]
command = "hostname -s"
format = "[\\($output\\)]($style) "
style = ""
when = 'test -n "$SSH_CONNECTION" && ! test -S "$SSH_AUTH_SOCK"'
