[settings]
experimental = false
disable_default_registry = true
disable_backends = ["asdf", "vfox"]
idiomatic_version_file_enable_tools = ["python", "npm", "bun"]
minimum_release_age = "7d"
paranoid = true
yes = true

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "bun"

[settings.github]
credential_command = "gh auth token"

[tool_alias]
# git
gh = "aqua:cli/cli"
ghq = "aqua:x-motemen/ghq"
lazygit = "aqua:jesseduffield/lazygit"
git-delta = "aqua:dandavison/delta"
git-lfs = "aqua:git-lfs/git-lfs"

# python
uv = "aqua:astral-sh/uv"
ruff = "aqua:astral-sh/ruff"
ty = "aqua:astral-sh/ty"
pytest = "pipx:pytest"

# pipx
zotero-mcp = "pipx:zotero-mcp"
docling = "pipx:docling"
pymupdf = "pipx:pymupdf"

# shell
starship = "aqua:starship/starship"
sheldon = "aqua:rossmacarthur/sheldon"

# ai
gemini = "npm:@google/gemini-cli"
codex = "aqua:openai/codex"

# devtools
lefthook = "aqua:evilmartians/lefthook"
nvim = "aqua:neovim/neovim"

# tools
chezmoi = "aqua:twpayne/chezmoi"
fastfetch = "aqua:fastfetch-cli/fastfetch"
fzf = "aqua:junegunn/fzf"
hyperfine = "aqua:sharkdp/hyperfine"
bat = "aqua:sharkdp/bat"
lsd = "aqua:lsd-rs/lsd"
tmux = "aqua:tmux/tmux-builds"
rg = "aqua:BurntSushi/ripgrep"
pandoc = "github:jgm/pandoc"
peco = "aqua:peco/peco"
swiftlint = "aqua:realm/SwiftLint"


[tools]
# programming languages
node = "lts"
deno = "latest"
pnpm = "latest"
bun = "latest"
python = "3.13"
rust = "latest"
cargo-binstall = "latest"
go = "latest"
ruby = "latest"
# php = "latest"
perl = "latest"
java = "latest"
typst = "latest"

# git
gh = "latest"
ghq = "latest"
lazygit = "latest"
git-delta = "latest"
git-lfs = "latest"
"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"

# python
uv = "latest"
ruff = "latest"
ty = "latest"
pytest = "latest"

# shell
starship = "latest"
sheldon = "latest"

# devtools
lefthook = "latest"
nvim = "latest"

# AI
gemini = "latest"
codex = "latest"
"npm:skills" = "latest"

# tools
fastfetch = "latest"
chezmoi = "latest"
fzf = "latest"
hyperfine = "latest"
bat = "latest"
lsd = "latest"
"aqua:sxyazi/yazi" = "latest"
usage = "latest"
tmux = "latest"
ffmpeg = "latest"
"npm:vercel" = "latest"
rg = "latest"
pandoc = "latest"
peco = "latest"
swiftlint = "latest"


[tasks.update]
description = "Update all tools"
depends = ["update:brew", "update:mise", "update:uv", "update:sheldon"]

[tasks."update:brew"]
run = ["brew update", "brew upgrade", "brew cleanup"]

[tasks."update:mise"]
run = [
	"mise plugin uninstall --all",
	"mise self-update -y",
	"mise upgrade -y",
	# "MISE_MINIMUM_RELEASE_AGE=7d mise prune --tools -y",
	"mise prune --configs -y",
]
[tasks."update:uv"]
run = ["uv tool upgrade --all", "uv cache prune -v"]

[tasks."update:sheldon"]
run = ["sheldon lock --update"]

[tasks.setup]
run = ["mise install", "sheldon lock --update"]
